-- Populate business_indicators table with essential data
USE bor_db;

-- Clear existing data (optional - remove this line if you want to keep existing data)
-- TRUNCATE TABLE business_indicators;

-- Primary business suffixes (highest weight - these are definitive business indicators)
INSERT INTO business_indicators (indicator_text, indicator_type, weight, is_active) VALUES
('Ltd', 'primary_suffix', 100, 1),
('Limited', 'primary_suffix', 100, 1),
('Inc', 'primary_suffix', 100, 1),
('Incorporated', 'primary_suffix', 100, 1),
('Corp', 'primary_suffix', 100, 1),
('Corporation', 'primary_suffix', 100, 1),
('LLC', 'primary_suffix', 95, 1),
('LLP', 'primary_suffix', 95, 1),
('Co', 'primary_suffix', 90, 1),
('Company', 'primary_suffix', 90, 1);

-- Secondary business indicators (medium to high confidence)
INSERT INTO business_indicators (indicator_text, indicator_type, weight, is_active) VALUES
('Sons', 'secondary_indicator', 80, 1),
('Bros', 'secondary_indicator', 80, 1),
('Brothers', 'secondary_indicator', 80, 1),
('Sisters', 'secondary_indicator', 75, 1),
('Services', 'secondary_indicator', 85, 1),
('Service', 'secondary_indicator', 85, 1),
('Shop', 'secondary_indicator', 85, 1),
('Store', 'secondary_indicator', 85, 1),
('Center', 'secondary_indicator', 75, 1),
('Centre', 'secondary_indicator', 75, 1),
('Clinic', 'secondary_indicator', 85, 1),
('Office', 'secondary_indicator', 70, 1),
('Group', 'secondary_indicator', 70, 1),
('Enterprise', 'secondary_indicator', 90, 1),
('Enterprises', 'secondary_indicator', 90, 1),
('Business', 'secondary_indicator', 90, 1),
('Restaurant', 'secondary_indicator', 95, 1),
('Cafe', 'secondary_indicator', 95, 1),
('Hotel', 'secondary_indicator', 95, 1),
('Motel', 'secondary_indicator', 95, 1),
('Inn', 'secondary_indicator', 90, 1),
('Garage', 'secondary_indicator', 85, 1),
('Auto', 'secondary_indicator', 80, 1),
('Automotive', 'secondary_indicator', 85, 1),
('Salon', 'secondary_indicator', 90, 1),
('Spa', 'secondary_indicator', 90, 1),
('Studio', 'secondary_indicator', 80, 1),
('Mart', 'secondary_indicator', 85, 1),
('Market', 'secondary_indicator', 85, 1),
('Pharmacy', 'secondary_indicator', 95, 1),
('Dental', 'secondary_indicator', 85, 1),
('Medical', 'secondary_indicator', 85, 1),
('Cleaners', 'secondary_indicator', 85, 1),
('Laundry', 'secondary_indicator', 85, 1),
('Bakery', 'secondary_indicator', 90, 1),
('Gallery', 'secondary_indicator', 80, 1),
('Boutique', 'secondary_indicator', 85, 1),
('Supplies', 'secondary_indicator', 80, 1),
('Supply', 'secondary_indicator', 80, 1),
('Repair', 'secondary_indicator', 85, 1),
('Repairs', 'secondary_indicator', 85, 1),
('Sales', 'secondary_indicator', 80, 1),
('Rental', 'secondary_indicator', 85, 1),
('Rentals', 'secondary_indicator', 85, 1),
('Consulting', 'secondary_indicator', 85, 1),
('Consultants', 'secondary_indicator', 85, 1),
('Solutions', 'secondary_indicator', 75, 1),
('Systems', 'secondary_indicator', 75, 1),
('Technologies', 'secondary_indicator', 80, 1),
('Industries', 'secondary_indicator', 85, 1),
('Manufacturing', 'secondary_indicator', 90, 1),
('Construction', 'secondary_indicator', 90, 1),
('Contracting', 'secondary_indicator', 90, 1),
('Electric', 'secondary_indicator', 85, 1),
('Electrical', 'secondary_indicator', 85, 1),
('Plumbing', 'secondary_indicator', 90, 1),
('Heating', 'secondary_indicator', 85, 1),
('Cooling', 'secondary_indicator', 85, 1),
('Landscaping', 'secondary_indicator', 90, 1),
('Roofing', 'secondary_indicator', 90, 1),
('Flooring', 'secondary_indicator', 90, 1),
('Painting', 'secondary_indicator', 85, 1),
('Insurance', 'secondary_indicator', 90, 1),
('Realty', 'secondary_indicator', 90, 1),
('Properties', 'secondary_indicator', 85, 1),
('Management', 'secondary_indicator', 75, 1),
('Associates', 'secondary_indicator', 75, 1),
('Partners', 'secondary_indicator', 75, 1),
('Partnership', 'secondary_indicator', 80, 1),
('Foundation', 'secondary_indicator', 85, 1),
('Institute', 'secondary_indicator', 85, 1),
('Academy', 'secondary_indicator', 85, 1),
('School', 'secondary_indicator', 90, 1),
('College', 'secondary_indicator', 90, 1),
('University', 'secondary_indicator', 95, 1),
('Bank', 'secondary_indicator', 95, 1),
('Credit Union', 'secondary_indicator', 95, 1),
('Financial', 'secondary_indicator', 85, 1),
('Investments', 'secondary_indicator', 85, 1),
('Trading', 'secondary_indicator', 80, 1),
('Wholesale', 'secondary_indicator', 85, 1),
('Retail', 'secondary_indicator', 85, 1),
('Distribution', 'secondary_indicator', 85, 1),
('Logistics', 'secondary_indicator', 85, 1),
('Transport', 'secondary_indicator', 85, 1),
('Transportation', 'secondary_indicator', 85, 1),
('Delivery', 'secondary_indicator', 85, 1),
('Shipping', 'secondary_indicator', 85, 1),
('Storage', 'secondary_indicator', 80, 1),
('Warehouse', 'secondary_indicator', 85, 1);

-- Stop words (words to skip in analysis - weight 0 or very low)
INSERT INTO business_indicators (indicator_text, indicator_type, weight, is_active) VALUES
('the', 'stop_word', 0, 1),
('of', 'stop_word', 0, 1),
('de', 'stop_word', 0, 1),
('la', 'stop_word', 0, 1),
('le', 'stop_word', 0, 1),
('du', 'stop_word', 0, 1),
('des', 'stop_word', 0, 1),
('et', 'stop_word', 0, 1),
('&', 'stop_word', 0, 1),
('and', 'stop_word', 10, 1), -- 'and' has slight weight as it can indicate business partnerships
('for', 'stop_word', 0, 1),
('to', 'stop_word', 0, 1),
('at', 'stop_word', 0, 1),
('in', 'stop_word', 0, 1),
('on', 'stop_word', 0, 1),
('by', 'stop_word', 0, 1),
('with', 'stop_word', 0, 1),
('from', 'stop_word', 0, 1),
('or', 'stop_word', 0, 1),
('but', 'stop_word', 0, 1),
('not', 'stop_word', 0, 1),
('all', 'stop_word', 0, 1),
('can', 'stop_word', 0, 1),
('her', 'stop_word', 0, 1),
('was', 'stop_word', 0, 1),
('one', 'stop_word', 0, 1),
('our', 'stop_word', 0, 1),
('out', 'stop_word', 0, 1),
('his', 'stop_word', 0, 1),
('has', 'stop_word', 0, 1),
('had', 'stop_word', 0, 1),
('were', 'stop_word', 0, 1),
('been', 'stop_word', 0, 1),
('have', 'stop_word', 0, 1),
('their', 'stop_word', 0, 1),
('a', 'stop_word', 0, 1),
('an', 'stop_word', 0, 1),
('as', 'stop_word', 0, 1),
('are', 'stop_word', 0, 1),
('is', 'stop_word', 0, 1),
('it', 'stop_word', 0, 1),
('its', 'stop_word', 0, 1),
('be', 'stop_word', 0, 1),
('being', 'stop_word', 0, 1);

-- Suite/unit indicators (low weight - these are address components)
INSERT INTO business_indicators (indicator_text, indicator_type, weight, is_active) VALUES
('Suite', 'secondary_indicator', 30, 1),
('Unit', 'secondary_indicator', 30, 1),
('Apt', 'secondary_indicator', 30, 1),
('Apartment', 'secondary_indicator', 30, 1),
('Room', 'secondary_indicator', 25, 1),
('Rm', 'secondary_indicator', 25, 1),
('Floor', 'secondary_indicator', 25, 1),
('Fl', 'secondary_indicator', 25, 1),
('#', 'secondary_indicator', 20, 1);

-- Verify the data was inserted
SELECT indicator_type, COUNT(*) as count, AVG(weight) as avg_weight
FROM business_indicators 
GROUP BY indicator_type
ORDER BY indicator_type;

-- Show sample of each type
SELECT * FROM business_indicators WHERE indicator_type = 'primary_suffix' LIMIT 5;
SELECT * FROM business_indicators WHERE indicator_type = 'secondary_indicator' LIMIT 5;
SELECT * FROM business_indicators WHERE indicator_type = 'stop_word' LIMIT 5;